<?php

namespace ToDate\Condition;

use PHPUnit\Framework\TestCase;

/**
 * Test class for FeatureInSetCondition.
 * Generated by PHPUnit on 2012-02-06 at 22:18:11.
 */
class FeatureInSetConditionTest extends TestCase
{

    /**
     * @covers ToDate\Condition\FeatureInSetCondition::__construct
     */
    public function testConstructorThrowsExceptionWithInvalidFeature()
    {
        self::expectExceptionObject(new \InvalidArgumentException('Features need to be one or more of "dDjlNSwzWFmMntLoYyeIOPTZ", but  "X" given'));
        new FeatureInSetCondition('X', 3);
    }

    /**
     * @covers ToDate\Condition\FeatureInSetCondition::__construct
     * @covers ToDate\Condition\FeatureInSetCondition::__toString
     */
    public function testToStringWithComplexFeature()
    {
        $c = new FeatureInSetCondition('Ymd', '20120412');
        self::assertEquals('"Ymd" = 20120412', (string) $c);
    }

}
